apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jmsfwk/php-yorkshire-jenkins-quickstart-javascript:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jmsfwk/php-yorkshire-jenkins-quickstart-javascript:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: php-yorkshire-jenkins-quickstart-javascript
        chartPath: charts/php-yorkshire-jenkins-quickstart-javascript
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jmsfwk/php-yorkshire-jenkins-quickstart-javascript'
          image.tag: '{{.DIGEST_HEX}}'
